# Jina la utendaji
name: Majaribio

# Wakati wa kuendesha
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Kazi za kufanya
jobs:
  jaribu:
    name: Jenga na Jaribu
    runs-on: ubuntu-latest

    steps:
      - name: Pakua msimbo
        uses: actions/checkout@v4

      - name: Weka Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Weka LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-18-dev libclang-18-dev clang-18
          echo "LLVM_SYS_180_PREFIX=/usr/lib/llvm-18" >> $GITHUB_ENV

      - name: Jenga
        run: cargo build --release

      - name: Jaribu
        run: cargo test
